### ISSUE TITLE
Suggestion regarding global variables on plugin initialization

### ISSUE THREAD

**Issue by TheLeoP** [nvim-neorocks/nvim-best-practices#1]
```lua
if not vim.g.did_my_rust_plugin_init then
    -- Initialise
end
vim.g.did_my_rust_plugin_init = true
```

Since this is an internal variable. Wouldn't it be better to use a Lua global variable, thus avoiding the Vimscript <-> Lua transformation overhead?

```lua
if not _G.did_my_rust_plugin_init then
    -- Initialise
end
_G.did_my_rust_plugin_init = true
```

I guess that a valid use case would be allowing users to disable loading of the plugin from vimscript without having to use `v:lua`

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for the suggestion. 

Personally, I like the vimscript interoperability (some people prefer to use vimscript over lua for configuration), and I think the overhead is negli

But I do think it's a good idea to mention `_G` as an alternative.

**Comment by mrcjkb** [comment]
Oh, I just realised you're referring to the plugin l and ftplugin scripts. 

That I definitely agree with, no question.
Thanks for the tip🙏😃

**Comment by TheLeoP** [comment]
> What do you think of a note like this:

If we are talking about `vim.g` in general (using it for configuration, for example) i would add something similar to this part of the help files (`:h lua-vim-variables`)

```lua
-- Note that setting dictionary fields directly will not write them back into
-- Nvim. This is because the index into the namespace simply returns a copy.
-- Instead the whole dictionary must be written as one. This can be achieved by
-- creating a short-lived temporary.

    vim.g.my_dict.field1 = 'value'  -- Does not work

    local my_dict = vim.g.my_dict   --
    my_dict.field1 = 'value'        -- Instead do
    vim.g.my_dict = my_dict         --
```



> Oh, I just realised you're referring to the plugin l and ftplugin scripts.
> 
> That I definitely agree with, no question. Thanks for the tip🙏😃

Thanks to you for the guide c:

**Comment by mrcjkb** [comment]
I've added `:h lua-vim-variables` to the comment where I say I prefer `vim.g` :smile:
